-- MySQL Script generated by MySQL Workbench
-- Mon Jun 10 20:40:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema emprestimo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema emprestimo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emprestimo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `emprestimo` ;

-- -----------------------------------------------------
-- Table `emprestimo`.`amigos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestimo`.`amigos` (
  `idamigos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `telefone` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idamigos`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `emprestimo`.`ferramentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestimo`.`ferramentas` (
  `idferramentas` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `marca` VARCHAR(45) NULL DEFAULT NULL,
  `custo` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`idferramentas`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `emprestimo`.`emprestimos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestimo`.`emprestimos` (
  `emprestimoid` INT NOT NULL AUTO_INCREMENT,
  `amigoid` INT NOT NULL,
  `ferramentaid` INT NOT NULL,
  `data_emprestimo` VARCHAR(45) NULL DEFAULT NULL,
  `data_devolucao` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`emprestimoid`, `amigoid`, `ferramentaid`),
  INDEX `amigoid_idx` (`amigoid` ASC) VISIBLE,
  INDEX `ferramentaid_idx` (`ferramentaid` ASC) VISIBLE,
  CONSTRAINT `amigoid`
    FOREIGN KEY (`amigoid`)
    REFERENCES `emprestimo`.`amigos` (`idamigos`),
  CONSTRAINT `ferramentaid`
    FOREIGN KEY (`ferramentaid`)
    REFERENCES `emprestimo`.`ferramentas` (`idferramentas`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
